"""Add date_received to grades

Revision ID: 5c562242fe3a
Revises: cc3a86a1f0f6
Create Date: 2024-12-11 19:19:12.971089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c562242fe3a'
down_revision: Union[str, None] = 'cc3a86a1f0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
